import 'package:flutter/material.dart';

const BUTTON_COLOR = Colors.deepPurple;
const FONT_COLOR = Colors.deepPurple;

const KEY_PREFERENCE_IDIOMA = "PREFERNCE_KEY_IDIOMA";
const IDIOMA_PORTUGUES = 0;
const IDIOMA_INGLES = 1;
const IDIOMA_ESPANHOL = 2;

const KEY_TERMO_USO = "KEY_TERMO_USO";
const KEY_POLITICA_USO = "KEY_POLITICA_USO";
const KEY_POLITICA_CONTESTACAO = "KEY_POLITICA_CONTESTACAO";

const KEY_PASSAGEIRO = "KEY_PASSAGEIRO";
const KEY_STATUS_PASSAGEIRO = "KEY_STATUS_PASSAGEIRO";
const STATUS_PASSAGEIRO_ONBOARD_1 = "ONBOARD_1";
const STATUS_PASSAGEIRO_ONBOARD_2 = "ONBOARD_2";
const STATUS_PASSAGEIRO_VALIDA_CONTA = "VALIDA_CONTA";
const STATUS_PASSAGEIRO_DOCUMENTO = "DOCUMENTO";
const STATUS_PASSAGEIRO_SENHA = "SENHA";

const INDICE_TELA_SPLASH = 0;
const INDICE_TELA_ON_BOARD = 1;
const INDICE_TELA_PRE_LOGIN = 2;
const INDICE_TELA_LOGIN = 3;
const INDICE_TELA_ESCOLHA_IDIOMA = 4;
const INDICE_TELA_TERMO_USO = 5;
const INDICE_TELA_LER_TERMO = 6;
const INDICE_TELA_LER_POLITICA_USO = 7;
const INDICE_TELA_LER_POLITICA_CONTESTACAO = 8;
const INDICE_TELA_PASSAGEIRO_CADASTRO_1 = 9;
const INDICE_TELA_PASSAGEIRO_CADASTRO_2 = 10;
const INDICE_TELA_VALIDA_CONTA = 11;
const INDICE_TELA_CADASTRO_DOCUMENTO = 12;
const INDICE_TELA_CADASTRO_SENHA = 13;
const INDICE_TELA_CAPTURA_IMAGEM = 14;
const INDICE_TELA_RECUPERA_SENHA = 15;
const INDICE_TELA_BEM_VINDO_MAPA = 16;


// const INDICE_TELA_ =;
// const INDICE_TELA_ =;
// const INDICE_TELA_ =;
