import 'package:flutter/material.dart';

const BUTTON_COLOR = Colors.blue;
const FONT_COLOR = Colors.blue;

const KEY_PREFERENCE_IDIOMA = "PREFERNCE_KEY_IDIOMA";
const IDIOMA_PORTUGUES = 0;
const IDIOMA_INGLES = 1;
const IDIOMA_ESPANHOL = 2;

const KEY_TERMO_USO = "KEY_TERMO_USO";
const KEY_POLITICA_USO = "KEY_POLITICA_USO";
const KEY_POLITICA_CONTESTACAO = "KEY_POLITICA_CONTESTACAO";

const INDICE_TELA_SPLASH = 0;
const INDICE_TELA_ON_BOARD = 1;
const INDICE_TELA_PRE_LOGIN = 2;
const INDICE_TELA_LOGIN = 3;
const INDICE_TELA_ESCOLHA_IDIOMA = 4;
const INDICE_TELA_TERMO_USO = 5;
const INDICE_TELA_LER_TERMO = 6;
const INDICE_TELA_LER_POLITICA_USO = 7;
const INDICE_TELA_LER_POLITICA_CONTESTACAO = 8;
// const INDICE_TELA_ =;
// const INDICE_TELA_ =;
// const INDICE_TELA_ =;
// const INDICE_TELA_ =;
// const INDICE_TELA_ =;
// const INDICE_TELA_ =;
