enum stateScreenEnum {
  SCREEN_IDLE,
  SCREEN_INSERT,
  SCREEN_SUCCESS,
  SCREEN_FAIL,
  SCREEN_LOADING,
  SCREEN_ESPERANDO_CONFIRMACAO_MOTORISTA,
  SCREEN_MOTORISTA_RECUSOU_VIAGEM,
  SCREEN_MOTORISTA_A_CAMINHO,
  SCREEN_MOTORISTA_ACEITOU_VIAGEM,
  SCREEN_EM_CORRIDA,
  SCREEN_EM_PAGAMENTO,
}

enum actionPassageiro {
     ACTION_LIVRE
   , ACTION_SOLICITACAO_PASSAGEIRO
   , ACTION_CORRIDA_RECUSADA_MOTORISTA
   , ACTION_CORRIDA_ACEITA_MOTORISTA
   , ACTION_MENSAGEM_PASSAGEIRO
   , ACTION_MENSAGEM_MOTORISTA
   , ACTION_CORRIDA_CANCELADA_PASSAGEIRO
   , ACTION_CORRIDA_CANCELADA_MOTORISTA
   , ACTION_CORRIDA_PAGAMENTO_PASSAGEIRO_MOTORISTA
   , ACTION_CORRIDA_PAGAMENTO_PASSAGEIRO_MOTORISTA_FAIL
   , ACTION_EM_CORRIDA_MACANETA
   , ACTION_EM_CORRIDA_PRE_AGENDADA
   , ACTION_ACAMINHO_PASSAGUEIRO
   , ACTION_CORRIDA_PAGAMENTO_NO_MOTORISTA
   , ACTION_FINAL_CORRIDA_MACANETA
   , ACTION_AGUARDANDO_SOLUCAO_PAGAMENTO
   , ACTION_PAGAMENTO_EFETUADO_NO_MOTORISTA
   , ACTION_LIVRE_COM_PAGAMENTO_MOTORISTA
}
