enum stateScreenEnum {
  SCREEN_IDLE,
  SCREEN_INSERT,
  SCREEN_SUCCESS,
  SCREEN_FAIL,
  SCREEN_LOADING,
  SCREEN_ESPERANDO_CONFIRMACAO_MOTORISTA,
  SCREEN_MOTORISTA_RECUSOU_VIAGEM,
  SCREEN_MOTORISTA_A_CAMINHO,
  SCREEN_MOTORISTA_ACEITOU_VIAGEM,
}
