//const URL_BASE_DEBUG = 'https://moovsp.com';
const URL_BASE_DEBUG = 'https://pacsis.ngrok.io';
const URL_BASE = 'https://moovsp.com';
const IS_DEBUG = true;
const BASE_APP_URL = '/moov';
const CHAVE_IV = 'Iud#9)deszvhjluE';

const END_POINT_LOGIN_PASSAGEIRO = '/passageiro/CEL_FLU_LOGIN_PASSAGEIRO';
const END_POINT_VERIFICA_EMAIL_PASSAGEIRO = '/passageiro/CEL_FLU_VERIFICA_EMAIL_PASSAGEIRO';
const END_POINT_VALIDA_EMAIL_PASSAGEIRO = '/passageiro/CEL_FLU_VALIDA_EMAIL_PASSAGEIRO';
const END_POINT_DOCUMENTO_PASSAGEIRO = '/passageiro/CEL_FLU_DOCUMENTO_PASSAGEIRO';
const END_POINT_SENHA_PASSAGEIRO = '/passageiro/CEL_FLU_SENHA_PASSAGEIRO';
const END_POINT_FOTO_PASSAGEIRO = '/passageiro/CEL_FLU_FOTO_PASSAGEIRO';
const END_POINT_LOGIN_PASSAGEIRO_EMAIL = '/passageiro/CEL_FLU_LOGIN_PASSAGEIRO_EMAIL';
